name: Linux Qt Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  linux-build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04

    steps:
      - uses: actions/checkout@v3

      - name: Prepare Environment (no timezone prompt)
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          apt-get install -y tzdata locales
          locale-gen en_US.UTF-8
          update-locale LANG=en_US.UTF-8

      - name: Install base dependencies
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          apt-get install -y \
            build-essential \
            cmake \
            ninja-build \
            patchelf \
            wget \
            curl \
            libglu1-mesa-dev \
            libegl1-mesa-dev \
            libgl1-mesa-dev \
            libxkbcommon-dev \
            libxkbcommon-x11-dev \
            libglib2.0-0 libglib2.0-dev \
            libdbus-1-dev \
            libfontconfig1-dev \
            libxcb-cursor0 libxcb-xinerama0 libxcb-util1 libx11-xcb1
            
            
      - name: Install required X11/XCB libraries
        run: |
          apt-get install -y \
            libxrender1 \
            libxrandr2 \
            libegl1 \
            libglu1-mesa \
            libgl1-mesa-dev \
            libxcb-render-util0 \
            libxcb-render0 \
            libxcb-image0 \
            libxcb-keysyms1 \
            libxcb-icccm4 \
            libxcb-shape0 \
            libxcb-xfixes0 \
            libxcb-sync1 \
            libxcb-randr0 \
            libxcb-util1 \
            libxcb-xinerama0 \
            libxcb-cursor0 \
            libxcb1-dev


      - name: Install PostgreSQL runtime (fixes libpq.so.5 not found)
        run: |
          apt-get install -y libpq-dev libpq5

      - name: Install Python & aqt
        run: |
          apt-get install -y python3 python3-pip
          pip3 install --upgrade pip
          pip3 install aqtinstall

      - name: Install Qt 6.5.3
        run: |
          aqt install-qt linux desktop 6.5.3 gcc_64 --outputdir Qt

      - name: Configure CMake
        run: |
          cmake -S . -B build -G Ninja \
            -DCMAKE_PREFIX_PATH=$GITHUB_WORKSPACE/Qt/6.5.3/gcc_64 \
            -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --parallel

      - name: Detect built executable
        id: findexe
        run: |
          EXE=$(find build -maxdepth 2 -type f -executable | head -n 1)
          echo "EXE=$EXE" >> $GITHUB_ENV
          echo "Found executable: $EXE"

      - name: Create AppDir structure
        run: |
          mkdir -p AppDir/usr/bin AppDir/usr/share/applications AppDir/usr/share/icons/hicolor/256x256/apps
          cp "$EXE" AppDir/usr/bin/MyQtApp
          chmod +x AppDir/usr/bin/MyQtApp

          cp deploy/app.png AppDir/usr/share/icons/hicolor/256x256/apps/MyQtApp.png

          cat <<EOF > AppDir/usr/share/applications/MyQtApp.desktop
          [Desktop Entry]
          Name=My Qt App
          Exec=MyQtApp
          Icon=MyQtApp
          Type=Application
          Categories=Utility;
          EOF

      - name: Download linuxdeploy & qt plugin
        run: |
          wget -q https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          wget -q https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage
          chmod +x linuxdeploy*.AppImage

      - name: Download linuxdeployqt (no fuse mode)
        run: |
          wget -q https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage -O linuxdeployqt
          chmod +x linuxdeployqt

      - name: Install MySQL Libraries
        run: |
           apt-get update
           apt-get install -y libmysqlclient-dev
           
           
      - name: Make linuxdeployqt executable
        run: chmod +x linuxdeployqt

      - name: Install unixODBC runtime
        run: |
          apt-get update
          apt-get install -y unixodbc unixodbc-dev odbcinst odbcinst1debian2


      - name: Build AppImage
        env:
          APPIMAGE_EXTRACT_AND_RUN: 1
        run: |
          export PATH="$GITHUB_WORKSPACE/Qt/6.5.3/gcc_64/bin:$PATH"
          chmod +x linuxdeployqt
          ./linuxdeployqt AppDir/usr/share/applications/MyQtApp.desktop \
            -bundle-non-qt-libs \
            -extra-plugins=imageformats/libqsvg.so \
            -extra-plugins=sqldrivers/libqsqlmysql.so \
            -appimage



      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyQtApp-Linux-AppImage
          path: "*.AppImage"

