// Theme.qml
pragma Singleton
import QtQuick 2.15
import "../"
QtObject {
    property color primary: "#23272e"
    property color bg: "#ffffff"
    property color text: "#262626"
    property color softgray: "#E0E0E0"
    property color accent: "#030213"
    property color borders: "#eaeaea"
    property color colorBlue:"#349bfd"
    property color softgrays : "#ececf0"
    property color microsoft :"#2563eb"
    property color txtcolor: "#333333"
    property color timetxt:"#888888"
    property color logininput: "#f5f5f5"
    property color smalltxt:"#888"
    property color danger:"#D32F2F"
    property color boldText:"#333"
    property color loaderrectanglecolor: "#A0A0A0C0"
    property color loadergradientcolor:"#63B3FF"
    property color colorRed:"#A30505"
    property color colorGreen:"#55A13A"
    property color colorYellow:"#E8E53C"
    property color colorPurple:"#2AA16D"
    property color colorOrange: "#FFA500"
    property color colorPink:   "#EF5DA8"
    property color colorTeal:   "#45B8AC"
    property color colorBrown:  "#8D5524"
    property color colorCyan:   "#00BFAE"
    property color colorNavy:   "#205375"
    property color colorGray:   "#7D7F7D"
    property color colorBeige:  "#FFF3CD"

    property string appTitle: "Productivity Tracker"
    property string date: Qt.formatDate(new Date(), "dddd, d MMMM yyyy")
    property string category:  "Category Breakdown"
    property string timelogtoday:  "Time Logged Today"
    property string timer: Qt.formatTime(new Date(0,0,0,0,0,TimerManager.seconds), "hh:mm:ss")
    property string signin : "Sign in to continue tracking your productivity"
    property string loginwithgoogletext:"Continue with Google"
    property string loginwithmicrosofttext: "Continue with Microsoft"
     property string lastscreenshot: "Last Screenshot Taken"
     property string signUp:"Sign Up Now"
    property string redirectsignup: "Travel while login, Click here."
}
